version: '3.7'

services:
  server:
    container_name: backend
    restart: always
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    links: 
      - mongo
    #volumes:- .:/usr/src/app
  
  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - "27018:27017"
    logging: 
      driver: none

  cliente: 
    container_name: fronend
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    expose:
      - "3000"